import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google"; // Import Mono font
import "./globals.css";

const mono = Roboto_Mono({ subsets: ["latin"] }); // Use Mono font

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={mono.className}>{children}</body> // Use Mono font here
    </html>
  );
}